### PR TITLE
Perform relabel (restorecon) using find to support regexes

### LINKED ISSUE #56: Better check for which folder to relabel possible?
This is more a question than an issue, because nothing is truly broken.
I have a fcontext for /var/lib/mysql-default(/.*)?
The relabel for this is a restorecon on /var/lib

Could the code that checks the path be rewritten so the restorecon would be done on /var/lib/mysql-default? Is there a list of special regex characters that could be trimmed from the end that should never be in folder names?

The question comes because a restorecon on /var/lib takes reaaaaally long

The fact that the condition uses the same command while not changing anything, doesn't help either. As far as I can see ATM this only means a run almost twice as long (in my case).

### PR DESCRIPTION
**Pull request by daften**
This replaces the shell_out with a find based command. It was still very fast for my use cases and works for regexes as well.
Fixes #56

### CODE REVIEW

**Comment by daften** [comment]
CC'ing @atward as well, since he was interested in the original issue #56

File: providers/fcontext.rb [hunk 1]
```diff
@@ -38,8 +38,10 @@ def semanage_options(file_type)
 
 # Run restorecon to fix label
 action :relabel do
-  res = shell_out!('restorecon', '-irv', new_resource.file_spec)
-  new_resource.updated_by_last_action(true) unless res.stdout.empty?
+  execute "selinux-fcontext-#{new_resource.secontext}-relabel" do
+    command "find / -regextype posix-egrep -regex '#{new_resource.file_spec}' -type d -print0  2>/dev/null | xargs -0 restorecon -iRv"
```
Comment (BackSlasher) [inline providers/fcontext.rb]: This worries me because of shell escaping interfering with the regex. We might need to escape it. I think the best way to handle this is using `shell_out` as it'll avoid shell expansion.
Also, `find BLABABA -exec restorecon -iRv {} \;` is better IMO

File: test/cookbooks/selinux_policy_test/recipes/fcontext.rb [hunk 2]
```diff
@@ -57,7 +59,27 @@
   action :delete
 end
 
-execute "restorecon #{dir_name}" # Restore original context
+# Testing regexes
```
Comment (BackSlasher) [inline test/cookbooks/selinux_policy_test/recipes/fcontext.rb]: good on you for adding the testing

File: providers/fcontext.rb (hunk 1 above)
Comment (daften) [inline providers/fcontext.rb]: pushing a new commit now. we do need find / -regex and all that stuff though

File: test/cookbooks/selinux_policy_test/recipes/fcontext.rb (hunk 2 above)
Comment (daften) [inline test/cookbooks/selinux_policy_test/recipes/fcontext.rb]: thanks. you did request it, so :)

File: providers/fcontext.rb [hunk 3]
```diff
@@ -38,7 +38,7 @@ def semanage_options(file_type)
 
 # Run restorecon to fix label
 action :relabel do
-  res = shell_out!('restorecon', '-irv', new_resource.file_spec)
+  res = shell_out!("find / -regextype posix-egrep -regex '#{new_resource.file_spec}' -execdir restorecon -iRv {} \\;")
```
Comment (BackSlasher) [inline providers/fcontext.rb]: One last suggestion - to avoid any chance of commas in regex breaking this, convert to the comma way of shell_out:
`('find','/','-regextype','posix-egrep','-regex',new_resource.file_spec,'-execdir','restorecon','-iRv', '{}', ';')`
There might be a more elegant way to express that (e.g. `%w{} + [new_resource.file_spec] + %w{}`)
This is just to bullet-proof the interpolation here

Comment (daften) [inline providers/fcontext.rb]: done :)

**Comment by BackSlasher** [comment]
thanks for the PR!
I hope this will solve the mystery issue.
@shortdudey123 hope it's OK I merged.

**Comment by shortdudey123** [comment]
Awesome sauce
